# -*- coding: utf-8 -*-
"""domainbed_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12BTH5Xnh2jlUSZXzUQtmONe3GwbHVqXM
"""

!pip install --quiet gdown timm wilds

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/facebookresearch/DomainBed.git /content/drive/MyDrive/domainbed_project/DomainBed

# %cd /content/drive/MyDrive/domainbed_project/DomainBed

!pip install torch torchvision numpy scipy scikit-learn pandas pillow tqdm

import torch
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")

from google.colab import files
files.upload()

import os, shutil

src_path = "/content/drive/MyDrive/domainbed_project/DomainBed/kaggle.json"
dst_path = "/root/.kaggle/kaggle.json"

os.makedirs('/root/.kaggle', exist_ok=True)

shutil.copy(src_path, dst_path)
os.chmod(dst_path, 0o600)

print("kaggle.json 已成功配置！")

!pip install kaggle
!kaggle datasets download -d ma3ple/pacs-dataset -p /content/drive/MyDrive/domainbed_project/

import zipfile

zip_path = "/content/drive/MyDrive/domainbed_project/pacs-dataset.zip"
extract_to = "/content/drive/MyDrive/domainbed_project/"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

print("Unzipped")

import os

old_path = "/content/drive/MyDrive/domainbed_project/kfold"
new_path = "/content/drive/MyDrive/domainbed_project/PACS"

if os.path.exists(old_path):
    os.rename(old_path, new_path)
    print("Successfully renamed kfold to PACS")
else:
    print("The kfold folder cannot be found. Please check that the path is correct.")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/domainbed_project/DomainBed

!python -m domainbed.scripts.train \
    --data_dir=/content/drive/MyDrive/domainbed_project \
    --algorithm ERM \
    --dataset PACS \
    --test_env 0 \
    --hparams '{"resnet18": true}'