name: dg-tta
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - numpy
  - matplotlib
  - pyyaml
  - tqdm
  - pip:
      - opencv-python
