experiment_name: test_tta_on_trained_custom_resnet50
seed: [42, 123, 2025]
device: cuda
eval_only: true
tta_strategy: custom

model:
  name: resnet50
  pretrained: true
  num_classes: 7
  checkpoint_dir: checkpoints/resnet50_custom_aug  # relative path to custom-trained model

data:
  dataset: PACS
  data_root: data/PACS  # relative path to PACS dataset
  target_domains: ["art_painting", "cartoon", "photo", "sketch"]
  batch_size: 32
  num_workers: 4

tta:
  transforms: ["resize", "horizontal_flip", "rotation"]
  fusion: mean_logits_softmax
  views: 3

eval:
  metric: accuracy
